language: ruby
rvm:
  - "2.1.2"

addons:
  postgresql: "9.3"

before_script:
  - psql -c 'create database travis_ci_test;' -U postgres

secure: "h1cEtSzHT0AU2yLRxy2Fzajl6gAUXPFVJuxrpQ4rpGUdtht0zCmgiUyqeHM86tJhkM+vMv02o0z0JJTDSFSZCE7vn7WmGyiO/+XDHn0QtdNDZE7ClR3LWvKCzpWMdMNOzzT9jjh4t79k4E4jDPScp8eAZm81ZN6ll35m9yuCaIQ="
