language: ruby
rvm:
- 2.1.2
env:
  global:
    secure: "gWFTgOmI43mD/ywe+gXshUmdWl2vCrHk0t/BeYJaWkQSXlpCytaswRGQ+TCybSRHKo0qGBsrnmTaBpF4vG5U7sgxSnGP6UOmRh2Z+7dx7E8RV5GeSIwwZx0l3A2KdTNhzTyCCT3KDR+uyQwRpTzGIRQ1kve+nN7U0PZ4vhZXmcc="
