default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  host: localhost
  username: ror
  password: postgres

development:
  <<: *default
  database: football_development

test:
  adapter: postgresql
  database: travis_ci_test
  username: postgres

production:
  <<: *default
  database: football_productions